### ISSUE TITLE
Scrobbling songs on wrong date and time.

### ISSUE THREAD

**Issue by AshBardhan** [taurheim/scrobblify#6]
After uploading my Spotify play history, The songs were supposed to be scrobbled on the day and time it was actually listened weeks ago. But instead, all of my songs scrobbled today at the same time.

Please fix this.

**Comment by taurheim** [comment]
Hey @AshBardhan , this is intended behaviour. Last.fm doesn't support scrobbling past 2 weeks ago. The solution is to scrobble any songs older than 2 weeks on the current date - this option is disabled by default but since you had this happen I assume you checked this box:

![image](https://user-images.githubusercontent.com/5691564/64195792-30dfb080-ce37-11e9-9bcb-c804452192e9.png)

**Comment by AshBardhan** [comment]
Ok, I get it. But put some caution or asterisk sign to indicate the user. 

E.g - 
```
[] **Scrobble tracks older than 2 weeks***
* This will show as listened to today.
```
